<#macro footer>
    <footer class="text-white py-2" style="background-color: #FF8C00; position: relative; bottom: 0; width: 100%; display: flex; justify-content: center; align-items: center;">
        <div class="container py-2">
            <a class="logo" href="/" style="display: flex; justify-content: center;">
                <span class="logo-item">Бюро знахідок</span>
            </a>
            <div class="text-center">
                <p class="mb-0">Київ, станція "Нивки" Святошинсько-Броварської лінія.</p>
                <p class="mb-0">+380 951 76 51 13</p>
                <p class="mb-0">2023-2024</p>
            </div>
        </div>
    </footer>
</#macro>






